# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This build config builds container images used in cloudbuild.yaml

steps:
- id: get
  name: 'tutum/curl' # ubuntu + curl
  args:
    - bash
    - -exc
    - |
      curl -Lo master.tar.gz https://github.com/GoogleCloudPlatform/cloud-builders-community/archive/master.tar.gz
      tar xfz master.tar.gz
- id: docker-build-pack
  name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --tag=gcr.io/${PROJECT_ID}/pack
  - cloud-builders-community-master/pack
  waitFor:
  - get
- id: docker-build-envsubst
  name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --tag=gcr.io/${PROJECT_ID}/envsubst
  - cloud-builders-community-master/envsubst
  waitFor:
  - get
images:
- gcr.io/${PROJECT_ID}/pack
- gcr.io/${PROJECT_ID}/envsubst
